[package]
name = "pong_game"
version = "0.1.0"
authors = ["David Jenkins <david.nicholas.jenkins@gmail.com>"]

[dependencies]
piston = "0.13"
piston2d-graphics = "0.11"
pistoncore-glutin_window = "0.16"
piston2d-opengl_graphics = "0.17"
